services:
  # MongoDB container
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - stocks-db:/data/db

  # Stocks1 container 1
  stocks1:
    build: 
      context: ./stocks1
      dockerfile: Dockerfile
    container_name: stocks1
    environment:
      - STOCKS_INSTANCE=stocks1
    volumes:
      - ./stocks1:/app
    ports:
      - "5001:8000"
    expose:
      - 8000
    restart: always
    depends_on:
      - mongo


  # Capital gains container
  cap_gains:
    build:
      context: ./capital_gains
      dockerfile: Dockerfile
    container_name: cap_gains
    ports:
      - "5003:8080"
    depends_on:
      - mongo
      - stocks1

volumes:
  stocks-db:
