name: assignment4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export stocks1 image
        uses: docker/build-push-action@v5
        with:
          context: ./stocks1
          file: ./stocks1/Dockerfile
          push: false
          tags: stocks1:latest
          outputs: |
            type=docker,dest=/tmp/stocks1_image.tar
      # Build and upload stocks and cap-gains image as artifacts
      - name: Build and export capital gains image
        uses: docker/build-push-action@v5
        with:
          context: ./capital_gains
          file: ./capital_gains/Dockerfile
          push: false
          tags: capital-gains:latest
          outputs: |
            type=docker,dest=/tmp/capital_gains_image.tar

      - name: Upload stocks1 image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: stocks1-image
          path: /tmp/stocks1_image.tar

      - name: Upload capital gains image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: capital-gains-image
          path: /tmp/capital_gains_image.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download stocks1 image artifact
        uses: actions/download-artifact@v4
        with:
          name: stocks1-image
          path: /tmp

      - name: Download capital gains image artifact
        uses: actions/download-artifact@v4
        with:
          name: capital-gains-image
          path: /tmp

      - name: Verify downloaded artifact
        run: ls -l /tmp

      - name: Load Docker images
        run: |
          docker load -i /tmp/stocks1_image.tar
          docker load -i /tmp/capital_gains_image.tar

      - name: List Docker images
        run: docker image ls

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
          
      - name: Delay 5 seconds
        run: sleep 5
        
      - name: Check containers running
        run: docker ps
  
  # set up python and pytest environment
      - name: Set up Python
        uses: actions/setup-python@v4
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Test with pytest
        run: |
          cd tests/
          pytest -v assn4_tests.py | tee test_results.txt

      - name: upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with: 
          name: GH_test_results
          path: tests/testresults.txt
