name: Assignment 4 Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create log file
        run: |
          echo "$(date -Iminutes)" > log.txt
          echo "Lior Nativ" >> log.txt  # Replace with actual submitter names

      - name: Build Docker images
        id: build_images
        run: |
          docker-compose -f docker-compose.yml build
          if [ $? -eq 0 ]; then
            echo "image successfully built" > log.txt
          else
            echo "image not able to be built" > log.txt
          fi
  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker Compose
        id: run_containers
        run: |
          docker-compose -f docker-compose.yml up -d
          if [ $? -eq 0 ]; then
            echo "Container up and running" >> log.txt
          else
            echo "Container failed to run" >> log.txt
          fi

      - name: Run tests
        id: run_tests
        run: |
          docker-compose exec cap_gains pytest > result.log || true
          docker-compose exec stocks1 pytest >> result.log || true
          cat result.log
          if grep -q "failed" result.log; then
            echo "tests failed" >> log.txt
          else
            echo "tests succeeded" >> log.txt
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: result.log

  query:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Execute queries
        run: |
          python query_script.py > query_results.log
          cat query_results.log

      - name: Upload query results
        uses: actions/upload-artifact@v4
        with:
          name: query-results
          path: query_results.log

      - name: Upload application log
        uses: actions/upload-artifact@v4
        with:
          name: application-log
          path: result.log

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: workflow-log
          path: log.txt
